In [3]:
%matplotlib inline

import random
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

### Reference for API of tensorflow
 - https://www.tensorflow.org/api_docs/

### Mathematic operation
 - reference:<br>
 https://www.tensorflow.org/versions/master/api_guides/python/math_ops#Arithmetic_Operators
 - 주요 API (기본 연산) <br>
     - tf.add(x,y): element-wise addition
     - tf.subtract(x,y): element-wise subtraction
     - tf.multiply(x,y): element-wise multiplication
     - tf.scalar_mul(scalar, x): multipy a scalar to x
     - tf.div(x,y): element-wise division 
     - tf.mod(x,y): element-wise remainder of division
 - 주요 API (산술 연산): <br>
     - tf.abs(), tf.neg(), tf.inv(), tf.square(), tf.sqrt(), tf.pow(),tf.log(), tf.ceil(), tf.floor(), tf.maximum(), tf.minimum(), tf.cos(), tf.sin(), tf.tan()
 - 주요 API (벡터/매트릭스 연산): <br>
     - tf.matmul(), tf.reduce_mean(), tf.reduce_sum(), reduce_min(), reduce_max(), 
 - 필요에 따라 API를 검색해서 사용해주세요.

#### Problem 1 세제곱수 및 제곱근 계산
  - 인풋은 float32 타입의 variable로 선언
  - 정답:<br>
  input: 
 [[1 2]
 [3 4]] <br>
세제곱수:  [[  1.   8.] [  27.  64.]] <br>
제곱근:  [[ 1.          1.41421354] [ 1.73205078  2.        ]]

In [ ]:
# TODO: 변수 정의
node1 = 

# TODO: 세제곱수 계산
node2 = 

# TODO: 제곱근 계산
node3 = 

inp = np.arange(1,5).reshape(2,2)
print("input: \n", inp)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    
    res1, res2 = sess.run([node2, node3], {node1:inp})
    print("세제곱수: \n", res1)
    print("제곱근: \n", res2)

#### Problem 2 매트릭스 element-wise 곱셈
  - [1 2] <br>
    [3 4] <br>
    \* <br>
    [3 4] <br>
    [5 6] <br>
    = <br>
    [3 8] <br>
    [15 24]    

In [12]:
# TODO: implement matrix element-wise multiplication

#### Problem 3 매트릭스 곱셈
  - [1 2] <br>
    [3 4] <br>
    \* <br>
    [3 4] <br>
    [5 6] <br>
    = <br>
    [13 16] <br>
    [29 36]    

In [14]:
# TODO: implement matrix multiplication

#### Problem 4 평균값 계산
  - input (2-dim matrix): <br>
    [1 2 3 4 5] <br>
    [6 7 8 9 10] <br>
  - output1 (모든 데이터에 대한 평균): 5.5 
  - output2 (각 행에 대한 평균): <br> [3.5, 4.5, 5.5, 6.5, 7.5] 
  - output3 (각 열에 대한 평균):<br> [3] <br> [8] 

In [ ]:
# TODO: implement 평균값 계산

#### Problem 5 softmax 구현
  - softmax$(x_i)=\frac{\exp^{x_i}}{\sum_{j=1}^{K}\exp^{x_i}}$

In [30]:
node1 = tf.placeholder(tf.float32)

# TODO: implement softmax
node2 = 

with tf.Session() as sess:
    inp = np.random.randn(1,10)
    print("softmax using tensorflow: \n", sess.run(node2, {node1:inp}))
    #print("softmax using tensorflow: \n", sess.run(node2, {node1:inp}))
    print("softmax using numpy: \n", np.exp(inp) / np.sum(np.exp(inp), axis=1))

softmax using tensorflow: 
 [[ 0.16992231  0.12765571  0.07094713  0.05544443  0.05057109  0.04449829
   0.06651492  0.35859632  0.0113751   0.04447464]]
softmax using numpy: 
 [[ 0.16992232  0.12765573  0.07094714  0.05544443  0.05057109  0.04449829
   0.06651492  0.35859633  0.0113751   0.04447465]]


#### Problem 6 L1 loss 정의
  - $y_i$: ground-truth label
  - $f(x_i)$: predicted label
  - $L = \sum_i{|y_i - f(x_i)|}$

In [14]:
# define ground-truth label
x = tf.placeholder(tf.float32)
true_label = tf.placeholder(tf.float32) # y

W = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
linear_model = W * x + b # f(x)

# TODO: define L1 loss
l1_loss = 

In [ ]:
cross_entropy_loss = -tf.reduce_sum(labels * tf.log(preds), reduction_indices=[1])

#### Problem 7 cross-entropy loss 정의
  - $y_i$: ground-truth label, one-hot vector
  - $f(x_i)$: predicted label
  - $L = -\sum_i{y_i \log(x_{i})}$

In [49]:
node1 = tf.placeholder(tf.float32)
node2 = tf.placeholder(tf.float32)

# TODO: implement cross-entropy loss
loss = -tf.reduce_sum(node2 * tf.log(node1), reduction_indices=[1])

with tf.Session() as sess:
    inp = np.abs(np.random.randn(1,10))
    label = np.zeros(10)
    label[np.random.randint(10)] = 1.0
    print("input prediction:\n", inp)
    print("label:\n", label, "\n")
    
    print("cross_entropy loss tensorflow: \n", sess.run(loss, {node1:inp, node2:label}))
    print("cross_entropy loss using numpy: \n", -np.sum(label*np.log(inp), 1))

input prediction:
 [[ 0.11235787  0.8681087   0.05679359  0.63635814  0.40980719  0.03008798
   0.06585013  0.64491219  0.15743517  0.27741525]]
label:
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.] 

cross_entropy loss tensorflow: 
 [ 1.28223979]
cross_entropy loss using numpy: 
 [ 1.28223979]
